version: '3'
services:
    api:
        container_name: player_session_manager_api
        build: .
        #restart: always
        expose:
            - 5000
            - 8000
        ports:
            - "8000:8000"
        working_dir: /app

    cassandra:
        container_name: sample-cassandra
        image: launcher.gcr.io/google/cassandra3
        ports:
        - '7000:7000'
        - '7001:7001'
        - '7199:7199'
        - '9042:9042'
        - '9160:9160'
        volumes:
        - ./cassandradata:/var/lib/cassandra